---
- hosts: dev
  become: True
  tasks:
  
    - name: Start the container
      docker_container:
        name: kd31967
        image: "kd31967/dockeransible:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8010:8080
